name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Specify the branch you want to trigger the workflow.

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/TaleemHub:latest .
        docker push ${{ secrets.DOCKER_USERNAME }}/TaleemHub:latest
